# Generated by Django 4.1.5 on 2023-05-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Roll", models.CharField(max_length=100)),
                ("Pointcost", models.IntegerField(default=1)),
                ("Size", models.IntegerField(default=1)),
                ("EraStarLeague", models.BooleanField(default=False)),
                ("EraSuccession", models.BooleanField(default=False)),
                ("EraClanInvasion", models.BooleanField(default=False)),
                ("EraFedCom", models.BooleanField(default=False)),
                ("EraDarkAge", models.BooleanField(default=False)),
                ("EraIlClan", models.BooleanField(default=False)),
                (
                    "MechImage",
                    models.URLField(
                        default="https://t3.ftcdn.net/jpg/03/45/05/92/360_F_345059232_CPieT8RIWOUk4JqBkkWkIETYAkmz2b75.jpg",
                        max_length=500,
                    ),
                ),
            ],
        ),
    ]
