# Generated by Django 4.1.5 on 2023-05-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechcmd", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mech",
            name="MechImage",
        ),
        migrations.AddField(
            model_name="mech",
            name="ImageMech",
            field=models.ImageField(default="", max_length=150, upload_to="uploads/"),
        ),
    ]
