# Generated by Django 4.1.5 on 2023-05-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechcmd", "0002_remove_mech_mechimage_mech_imagemech"),
    ]

    operations = [
        migrations.AddField(
            model_name="mech",
            name="MechModel",
            field=models.CharField(default="", max_length=100),
        ),
    ]
