# Generated by Django 4.1.5 on 2023-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechcmd", "0004_alter_mech_imagemech"),
    ]

    operations = [
        migrations.AddField(
            model_name="mech",
            name="Armor",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mech",
            name="Skill",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mech",
            name="Structure",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mech",
            name="Pointcost",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mech",
            name="Size",
            field=models.IntegerField(null=True),
        ),
    ]
