# Generated by Django 4.1.5 on 2023-05-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mechcmd", "0005_mech_armor_mech_skill_mech_structure_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mech",
            name="Skill",
        ),
    ]
